### ISSUE TITLE
Don't show the text added after the pipe character

### ISSUE THREAD

**Issue by Stryn** [eggpi/citationhunt#64] opened 2016-11-22 16:07 UTC
On Finnish Wikipedia we sometimes write a reason (or a date when the template is added) for the citation needed template by adding text after the pipe character, for example `{{lähde|2.10.2016}}`. I noticed that those texts after the pipe character are shown in the Citation Hunt, and IMO they should not be visible in the tool.

Example sentence from [https://fi.wikipedia.org/wiki/FARC#Tavoitteet_ja_ideologia](url) as seen on the tool:
Yhdysvallat ja Euroopan unioni luokittelevat järjestön terroristijärjestöksi.2.10.2016`[lähde?]`

**Comment by eggpi** [comment] 2016-11-22 16:33
Good catch, this is definitely a bug! It should be a very simple fix - I've also had to do this for Swedish, but this is not a universal behavior, since other languages such as French do include useful information after the pipe.

Would you like to give this a try? If you think that would be fun, I can give you instructions for how to reproduce this in a simple way, fix it and add a test (and if you encounter problems following them, I'll definitely want to hear about them!). Otherwise, I'll just fix this myself in a couple of days.

**Comment by Stryn** [comment] 2016-11-22 16:39
Okay, I'm ready to try how it goes if you can give some instructions :-)

**Comment by eggpi** [comment] 2016-11-22 17:15
OK, so the code that processes articles and extracts snippets from them lives under the [snippet_parser](https://github.com/eggpi/citationhunt/tree/master/snippet_parser) directory. In it, you will see (among other things), a few files named after language codes, such as `fr.py` and `en.py`. These are used to implement language-specific behaviors, and we'll need to create a `fi.py` file to fix this bug.

#### Reproducing the problem

If you're comfortable using git and running Python programs through the command line, there's a nice way to reproduce this problem and make sure you've fixed it. Otherwise, just skip this part.

Try [these instructions](https://github.com/eggpi/citationhunt/tree/master/snippet_parser) up until the part that says "You're nearly ready to run the server" (you need to install the dependencies, but you shouldn't need anything after that).

Then, it should be very easy to reproduce the problem: the [snippet_parser/snippet_parser.py](https://github.com/eggpi/citationhunt/blob/master/snippet_parser/snippet_parser.py) file can be run from the command line to test the parsing of any given article. For example, with the following command line:

```
CH_LANG=fi python snippet_parser/snippet_parser.py FARC
```

you should see the snippets we've found for your example article, along with their corresponding sections. You should see the text after the pipe there, as we haven't fixed the problem yet!

#### Fixing the problem

You can now create a `fi.py` file with code to remove the content after the pipe. I'm fairly certain you can just copy `sv.py`, since the behavior is exactly the same in Swedish, but feel free to poke around these files to understand how they work if you're curious (it's a bit messy).

If you did the section above, you can run the above command again to make sure it's fixed. Bonus points if you also add a `fi_test.py` file with a simple unit test (you can copy code from `en_test.py` or `fr_test.py` for inspiration), but this is optional.

If you skipped the section above, I think you can just create the `fi.py` file and drag-and-drop it into the `snippet_parser` directory on GitHub, but I've never tried that myself.

Either way, just send me a pull request and I'll be happy to take a look. Thanks!

**Comment by Stryn** [comment] 2016-11-22 17:30
Thanks for the detailed instructions!

I'm not comfortable with python or git, but anyway wanted to try.
Is the "these instructions" link correct btw?

**Comment by eggpi** [comment] 2016-11-22 17:43
No worries, I've been meaning to write this documentation for a while, I'll just move it somewhere even if you don't use it :)

You're right, that link should point to: https://github.com/eggpi/citationhunt/blob/master/CONTRIBUTING.md#setting-up-a-local-citation-hunt . I've fixed it above too.

**Comment by eggpi** [comment] 2016-11-22 18:20
Fixed by #65:

https://tools.wmflabs.org/citationhunt/fi?id=97044900
https://tools.wmflabs.org/citationhunt/fi?id=f00c0b1c

Thanks!

**Closed by eggpi** 2016-11-22 18:20 UTC
